test_that("periodo_is_the_only_param() works for all elegir_*()", {
  df <- seguimiento_ep() |> elegir_periodo_anual()
  test_periodo_is_the_only_param <- function(x) get_query(x) |> purrr::flatten() |> periodo_is_the_only_param()
  expect_true(df |> test_periodo_is_the_only_param())
  expect_false(df |> elegir_quien_gasta("todos") |> test_periodo_is_the_only_param())
  expect_false(df |> elegir_con_que_se_financia("todos") |> test_periodo_is_the_only_param())
  expect_false(df |> elegir_como_se_estructura("todos") |> test_periodo_is_the_only_param())
  expect_false(df |> elegir_cuando_se_hizo_gasto("todos") |> test_periodo_is_the_only_param())
  expect_false(df |> elegir_donde_se_gasta("todos") |> test_periodo_is_the_only_param())
  expect_false(df |> elegir_en_que_se_gasta("todos") |> test_periodo_is_the_only_param())
})
